# Generated by Django 2.2.2 on 2019-06-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190628_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.FloatField(help_text='Temperature', null=True),
        ),
    ]
