# Generated by Django 2.2.2 on 2019-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20190628_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.DecimalField(decimal_places=2, help_text='Temperature', max_digits=4, null=True),
        ),
    ]
